# Generated by Django 6.0 on 2025-12-24 10:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="license",
            name="status",
            field=models.CharField(
                choices=[
                    ("valid", "Valid"),
                    ("suspended", "Suspended"),
                    ("cancelled", "Cancelled"),
                ],
                default="valid",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("idempotency_key", models.CharField(max_length=255)),
                ("response_data", models.JSONField()),
                ("status_code", models.IntegerField()),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="licenses.brand"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["brand", "idempotency_key"],
                        name="licenses_id_brand_i_8b689c_idx",
                    )
                ],
                "unique_together": {("brand", "idempotency_key")},
            },
        ),
    ]
